name: openmosaic-3.7
channels:
    - conda-forge
dependencies:
    - python=3.7.*
    - setuptools>=41.2
    - numpy>=0.17.1
    - xarray>=0.15.1
    - pint>=0.13
    - metpy>=0.12.1
    - cartopy=0.17.0
    - pandas>=1.0
    - netCDF4>=1.5.3
    - zarr>=2.4
    - arm_pyart>=1.11.1
    - wradlib>=1.7.3
    - requests>=0.24.0
    - dask>=2.20.0
    - xesmf>=0.3.0
    - pytest>=5.4.3
    - flake8>=3.8.3
    - black>=19.9
    - isort>=5.0.7
