name: openmosaic-3.8
channels:
    - conda-forge
dependencies:
    - python=3.8.*
    - setuptools>=41.2
    - numpy>=0.17.1
    - xarray>=0.15.1
    - pandas>=1.0
    - zarr>=2.4
    - arm_pyart>=1.12.2
    - wradlib>=1.7.3
    - requests>=0.24.0
    - dask>=2.20.0
    - pytest>=5.4.3
    - flake8>=3.8.3
    - black>=19.9
    - isort>=5.0.7
    - fsspec
    - s3fs
    - mypy_extensions >= 0.4.2
    - aiohttp
