# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup conda environment
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
        environment-file: ci/environment-${{ matrix.python-version }}.yml
        activate-environment: openmosaic-${{ matrix.python-version }}
        auto-activate-base: false

    - name: Install from source
      shell: bash -l {0}
      run: pip install -q --no-deps -e .

    - name: List packages in environment
      shell: bash -l {0}
      run: conda list

    - name: Run tests
      shell: bash -l {0}
      run: pytest
